# Available at https://github.com/gbaptista/sweet-moon-test

luarocks:
  path:
    - /home/me/.luarocks/share/lua/5.4/?.lua
    - /home/me/.luarocks/share/lua/5.4/?/init.lua
    - /home/me/.luarocks/lib/lua/5.4/?.so
  expected: ['supernova', 'dkjson', 'lfs']

jit:2.0.5:
  description: 'Lua Jit 2.0.5 + Fennel 1.0.0'
  shared_object: /home/me/sweet-moon-test/libluajit.so.2.0.5
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.4.4:
  description: 'Lua 5.4.4 + Fennel 1.0.0'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.4.4
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.4.2:
  description: 'Lua 5.4.2 + Fennel 1.0.0'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.4.2
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.3.3:
  description: 'Lua 5.3.3'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.3.3
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.2.4:
  description: 'Lua 5.2.4'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.2.4
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.1.5:
  description: 'Lua 5.1.5'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.1.5
  fennel: /home/me/sweet-moon-test/fennel-100.lua

5.0.3:
  description: 'Lua 5.0.3'
  shared_object: /home/me/sweet-moon-test/liblua.so.5.0.3

4.0.1:
  description: 'Lua 4.0.1'
  shared_objects:
    - /home/me/sweet-moon-test/liblua.so.4.0.1
    - /home/me/sweet-moon-test/liblualib.so.4.0.1

3.2.2:
  description: 'Lua 3.2.2'
  shared_object: /home/me/sweet-moon-test/liblua.so.3.2.2

'?':
  description: 'Lua ?'
  shared_object: /home/me/sweet-moon-test/liblua.so
